### PR TITLE
React wrapper updates

### PR DESCRIPTION
**Pull request by Akash-Mair**
Updated the react wrapper recipe to a 'minimal template'

### CODE REVIEW

**Comment by isaacabraham** [comment]
I think, if you're going to use a sample that's as lightweight as you now have, you should at least provide some "best practice" for creating react wrappers - perhaps as a second part e.g. either link to a sample or show directly in the recipe how you would abstract the props into a dedicated class with members.

Also consider providing a *simple* explanation of when to use `import` vs `importDefault` vs  `importAll`?

**Comment by Akash-Mair** [comment]
I've added a comparison for import, importAll, importDefault thought a visual would be a good indication which to use and when, for the "best practice" react wrapper I can link it to my blog once thats ready which will be splitting the component into another file with members for each prop and creation

**Comment by isaacabraham** [comment]
@Akash-Mair have you pushed?

**Comment by olivercoad** [comment]
The explanation of imports is really good. It might be worth putting it in https://safe-stack.github.io/docs/recipes/javascript/import-js-module/ as it relates to all javascript imports, not just react.

Could you please not remove the part that explains how to use a typed props list.
Or at least add a note to mention that it's possible to use a typed props list or record, with a link to https://github.com/fable-compiler/fable-react/blob/master/docs/using-third-party-react-components.md

**Comment by olivercoad** [comment]
For v3 #201 should we feature the `[<ReactComponent(import=...)>]` syntax (see https://zaid-ajaj.github.io/Feliz/#/Feliz/UsingJsx)

**Comment by isaacabraham** [comment]
@olivercoad agreed - @Akash-Mair could you undelete the Fable React section - some people prefer that style. This PR should just simplify / update the Feliz bit.

**Comment by Akash-Mair** [comment]
Thanks for the feedback @olivercoad , @isaacabraham will get on that now :)

**Pull request merged**
