### PR TITLE
Add Fable.Reaction to list of options

### PR DESCRIPTION
**Pull request by theimowski**
Docs for https://github.com/SAFE-Stack/SAFE-template/pull/168

### CODE REVIEW

**Comment by theimowski** [comment]
This is now ready to go

**Comment by isaacabraham** [comment]
@theimowski should we merge this? Also - we need a docs page on Reaction in SAFE that describes the difference between the two models (pros / cons / when to use what etc.)

**Comment by theimowski** [comment]
Yes please do merge - the option is already in template

**Comment by theimowski** [comment]
And regarding difference between the two models, maybe @dbrattli can help us a bit here?

**Pull request merged**
