### PR TITLE
Add Elmish.Brige docs

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
@Nhowka I had a go at the Elmish.Bridge docs, I didn't go in-depth, it was just a *what and why* section with a bit of taste of the how the code would look like. I chose a familiar code snippet of how a `GET` request would look like in message passing style, Maybe you know a better illustrative example, can you please review :smile:?

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
> Is there a chance you could add a small section on potential cases where it's not suitable for and / or explain how this might work in a load-balanced environment i.e. multiple web servers - is there anything that needs to be considered? Even if we don't provide solutions, just pointing out what the potential issues may be is a great start.

Definitely important as well, added in the latest commit! Let me know something is missing ;)

**Comment by Nhowka** [comment]
I love it! Maybe the part where it says that the state is _gone for good_ is a little scary. There is an option to set a message that will be dispatched on disconnection. The client could use it to persist most of the data that it has access and then send it back to the server when it reconnects.

Even without a built-in persistence there could be a manual way to recover, maybe _reset to the initial_ would be less scary?

**Comment by isaacabraham** [comment]
@Zaid-Ajaj This is looking great!

@Nhowka are sessions "sticky" between client / server (because of web sockets) or can web-socket get redirected within a load-balanced server cluster?

I think regarding the "gone for good" - it's not wrong :-) but perhaps simply stating that there is no built-in support for persistance or resilience of client / server state might be enough? Even with the disconnection message, I imagine that this still relies on the client manually persisting state (and then the server would have to know how to rehydrate its internal state based on the client message - could be tricky?). But redis / blobs / tables etc. are a good option for storing this.

**Comment by Nhowka** [comment]
@isaacabraham Usually the server will have little state, most of the time the relevant part is the auth related data. That could be saved on a JWT based token. If there's more server relevant data redis and similar probably could use that token to retrieve the data.

As for the load-balancing, I don't have information. I believe that it will change protocols once and keep the same connection for its lifetime.

**Comment by isaacabraham** [comment]
I suppose the main benefit from server side is being able to keep track of the clients and then potentially send messages out to them as broadcasts? Is there a way to persist *that* information? I suppose that's the bit with the load balancing - if there's no "global" list of clients then broadcasts from a single server can't be sure it's the full list.

**Comment by isaacabraham** [comment]
I'm happy to accept this as-is and maybe just make a few small modifications before pushing, if you both are?

**Comment by Nhowka** [comment]
@isaacabraham That's something that I added just because it would be a requested feature, and in my option highly secondary. But the `ServerHub` is not something inside the scope and it keeps a reference to the client/server dispatch and the server model.

The dispatches depends on the connection, so they have no use persisting. You could have another broadcast server that will send a message to all the local server and it will broadcast for all its local clients. Probably the same solutions that exists for this problem will work as well.

**Comment by Zaid-Ajaj** [comment]
@Nhowka I get what you mean, but in the end, any serious developer would rather know about the cons of the "new hot stuff" before actually diving in and using. The "scared" users will be those who want everything to work out-of-the-box without involving any effort. 

Ok that was just my 2 cents, I changed that block, it is good to merge now? You can always fine-tune the text later :wink:

**Comment by Nhowka** [comment]
@Zaid-Ajaj It was good already, just afraid of the _gone for good_ being read as _impossible_ to recover instead of _kinda annoying_ to recover. I'll add bits later about the state recovery and strategies to auto-login after a disconnection.

And really thank you! ❤ I hope that after a lot of practice I can write a documentation that user-friendly!

**Comment by isaacabraham** [comment]
closes #56

**Comment by isaacabraham** [comment]
Thanks both!

**Pull request merged**
