### PR TITLE
missing links clean up

### PR DESCRIPTION
**Pull request by RicoSaupe**
I moved topic pages into their own folders and fixed already existing missing links.

please review
@isaacabraham 
@OutOfScopeia

### CODE REVIEW

**Comment by RicoSaupe** [comment]
Also suggesting to split img folder and move images to where they are references faq/img, components/img and so on. Makes for an easier dependency handling and editing experience.
What do you think?

**Comment by RicoSaupe** [comment]
inspired by #309  by @Alkasai changed rest of dotnet new -i to install but left changes of  #309 alone to not cause conflict. please merge both

**Comment by mattgallagher92** [comment]
Thanks @RicoSaupe! We didn't get a chance to look at this this week, but will check it out soon!

**Comment by RicoSaupe** [comment]
@mattgallagher92 would be great otherwise and I can see that already we get conflicts with PRs coming in later but doing duplicated changes.

**Pull request closed without merging**
