### PR TITLE
Update quickstart.md with npm instructions

### PR DESCRIPTION
**Pull request by wezeku**
Update quickstart.md with instructions for creating a SAFE project for use with npm.

### CODE REVIEW

**Comment by theimowski** [comment]
I'd rather stick to the defaults in quickstart section.
We already have https://safe-stack.github.io/docs/template-overview/#js-deps which explains in detail all possible options

**Comment by wezeku** [comment]
In that case, maybe it would be a good idea to change the last bullet point in "Install pre-requisites" from "yarn (>= 1.10.1) or npm" to read just "yarn (>= 1.10.1)"? That would save some trouble shooting for those who just install npm when going through the guide (it didn't take much time to find the --js-deps option, but still...).

**Comment by theimowski** [comment]
Right this is an interesting point, I haven't considered that.
IMO we're better off simplifying the instructions, i.e. leave only `yarn` in prerequisites then.
@isaacabraham what's your take on that?

**Comment by isaacabraham** [comment]
No objections.

**Comment by isaacabraham** [comment]
@theimowski i'll merge and release this tonight unless you have an objections?

**Comment by theimowski** [comment]
Well my intent was not to change `quickstart` but rather `prerequisites` to keep it as simple as possible.
But as it's a very minor thing, we can go either way really - this PR improves current state

**Comment by isaacabraham** [comment]
@theimowski confused now :-) I think the issue is that the pre-requisites directly above state you can install either yarn or npm, but then then creation steps show how to do it for Yarn only, but doesn't mention it's for Yarn. So someone could install NPM, then run the steps and it won't work.

I think actually now that we should either:

1. Accept this PR, or 
2. Change the wording in the prerequisites to only give yarn instructions - and then have a link below (or elsewhere) for how to work with NPM.

**Comment by theimowski** [comment]
That's exactly what I meant, and I'm a bit in favour of the second option, but as said it's a minor thing so first option is OK too :)

**Comment by isaacabraham** [comment]
I'm in favour of option 2 as well. I think that that would be simpler.

**Comment by wezeku** [comment]
If the goal is to keep Quickstart as short and concise as possible, I'd prefer option 2 as well.

**Pull request closed without merging**
