### PR TITLE
Some love for the outdated docs

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
A lot of the code is updated, here is an overview

```
// Before
As an alternative to raw HTTP, you can also use the [Fable.Remoting]

// After
Alongside raw HTTP, you can also use [Fable.Remoting]
```
this is because remoting exposes a single `HttpHandler` that can be plugged into the application pipeline

> However, note that Fable Remoting is not designed for use as an "open" API for consumption by multiple client. It also forces all HTTP traffic to be delivered as a POST, which cannot be cached by the browser.

I removed this because this is simply incorrect as remoting uses GET for record fields of type `Async<T>` and `unit -> Async<T>` (no parameters required) and for other field types it uses POST 

As to being "open" or "closed": remoting is not using any magical headers or something like that for the [raw communication](https://zaid-ajaj.github.io/Fable.Remoting/src/raw-http.html) under the hood, for external consumers it works just like they expect with normal requests, only response status codes are limited to 200 and 500 so it is not fully RESTful. 

also see [type-safe documentation](https://zaid-ajaj.github.io/Fable.Remoting/src/docs.html) of the library that uses the bare-bones HTTP protocol to make requests to server

### CODE REVIEW

**Comment by isaacabraham** [comment]
@Zaid-Ajaj thanks for this! And yes, the Remoting docs are out of date now - when it first came out, I think it was at that point POST only. Great to see that it's even better now :-)

**Comment by Zaid-Ajaj** [comment]
@isaacabraham Thank you for replying and merging the PR! The docs aren't evolving as fast as the safe template nor it's components, IMO it should be the other way around. Maybe add @theimowski as a collaborator to this repo? I don't mind becoming a maintaner of this repo either :smile:

**Comment by theimowski** [comment]
I did spoil the docs website a couple of times due to having a different version of mkdocs installed. 
Currently I can't even preview the docs:

```
$  mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs

Aborted with 1 Configuration Errors!
```

which is strange as the material theme seems to be installed:
```
$ pip list
Package            Version
------------------ -------
...
mkdocs             1.0
mkdocs-material    3.0.6
pip                18.1
...
```

**Comment by isaacabraham** [comment]
I think I saw this a while back - I had the wrong deps installed (or had the wrong mkdocs version).

**Pull request merged**
