### PR TITLE
Heroku information

### PR DESCRIPTION
**Pull request by Nhowka**
Replaces #60

### CODE REVIEW

**Comment by Nhowka** [comment]
Is there anything blocking I could help?

**Comment by Zaid-Ajaj** [comment]
@theimowski Maybe tweet about this greatness, now having heroku and iis as deployment options? (actually just heroku greatness, no one cares about iis :joy:)

**Comment by theimowski** [comment]
sure: https://twitter.com/theimowski/status/1132323591675174913

**Pull request merged**
