### PR TITLE
[WIP] Intro to Functions

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
Cc @MikhailShilkov

**Comment by isaacabraham** [comment]
I feel that the alternative way of deploying should be shown as well i.e. raw HTTP upload - this negates the need to install any of the functions tooling on your build machine etc. Happy to add that in if you like?

**Comment by isaacabraham** [comment]
"syncing of triggers and stuff"? My understanding was that it simply wraps the HTTP upload mechanism - which is what functions exposes to deploy code into it.

**Comment by forki** [comment]
Looks like it does more.

Anyway if you want to test locally you need the core tools anyway

Isaac Abraham <notifications@github.com> schrieb am Sa., 28. Juli 2018,
15:41:

**Comment by isaacabraham** [comment]
Link?
________________________________

**Comment by forki** [comment]
ok lets start wit that and look how it looks. will update it then

**Pull request merged**
