### PR TITLE
Awesome list v2

### PR DESCRIPTION
**Pull request by Akash-Mair**
- [x] Keep the title of each component as just the title. This keeps the TOC clean, too. 
- [x] I suspect most people would want to go to the website to read about the package rather than the NuGet page.
- [x] Consider putting a short section at the top which links to the section on Femto or adding client packages.
- [x] Update this page to link here, rather than the Nuget search.
- [x] I would split up the Components section, or at the very least rename to "UI Controls" or similar.
- [x] Consider renaming the page to "SAFE-Compatible UI Components" or similar - SAFE Components on its own is too generic. 
- [x] Consider changing the opening text to something like "A set of SAFE-ready wrappers around existing React and JS UI Components" or similar.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi @Akash-Mair, I was just going through the docs on the on SAFE components and noticed that Feliz.AntDesign (one of my repos) is listed there but it is far from finished, in fact is it like 5% done and I don't think users will be happy it 😅 

A suggestion on the list and this is something I discussed with @isaacabraham a few times is to encourage library authors to make their library easier to use from Fable and potentially helping them doing so by, especially since this is the _curated_ SAFE list of packages:
 - Adding a README with installation instructions when missing (usually there is a nice README)
 - Adding femto metadata to the projects when missing (lots of these packages don't have the metadata 😞)
 - Adding documentation with sample code on the various use cases (would be nice)
 - Adding _live_ documentation website with sample code (would be great, but of course requires a bit of effort)

**Comment by Akash-Mair** [comment]
Thanks @Zaid-Ajaj! I did think some libraries may be unfinished my thinking was to show people that there are a lot of options when it comes to using the SAFE Stack but youre right that this is a curated list so should be more selective of whats on there or have some kind of disclaimer against incomplete projects that may still add value.

For now would it be worth dialling back the list for the projects that meet majority of the requirements to get that listed? 
Then start reaching out to the remaining library authors?

**Comment by isaacabraham** [comment]
@Akash-Mair or submitting PRs ourselves :-)

@zaid-ajaj My main worry about these lists is duplicating effort e.g on the Feliz site etc. - but agree 100%, working samples are great and the more of those we can have, the better.

**Comment by olivercoad** [comment]
Is there a list of "real world" websites that use fable somewhere? Just thinking it would be nice to have a list of sites that actually use these components in production.

**Comment by isaacabraham** [comment]
@olivercoad I'd love that - can you create a separate issue for this?

**Pull request merged**
